# Generated by Django 6.1.1 on 2026-09-30 15:37

import apps.marketplace.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('bakery', 'Bakery & Pastries'), ('meals', 'Prepared Meals & Combos'), ('desserts', 'Desserts & Sweets'), ('beverages', 'Beverages & Juices'), ('snacks', 'Snacks & Quick Bites'), ('grocery', 'Dairy & Fresh Produce')], db_index=True, default='bakery', max_length=40)),
                ('image', models.URLField(blank=True, default='assets/images/bakery_box.jpg', help_text='Food image URL or relative asset path', max_length=500)),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('discounted_price', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('quantity', models.PositiveIntegerField(help_text='Total quantity initially made available', validators=[django.core.validators.MinValueValidator(1)])),
                ('quantity_available', models.PositiveIntegerField(help_text='Remaining available quantity for booking')),
                ('pickup_start', models.CharField(default='7:00 PM', help_text='e.g., 7:00 PM or 19:00', max_length=50)),
                ('pickup_end', models.CharField(default='9:00 PM', help_text='e.g., 9:00 PM or 21:00', max_length=50)),
                ('pickup_instructions', models.TextField(blank=True, default='Show your booking ID at the counter during the pickup window.')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('sold_out', 'Sold Out'), ('expired', 'Expired')], db_index=True, default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'food_listings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_number', models.CharField(db_index=True, default=apps.marketplace.models.generate_booking_number, max_length=30, unique=True)),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('READY_FOR_PICKUP', 'Ready for Pickup'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='CONFIRMED', max_length=25)),
                ('payment_status', models.CharField(choices=[('PAYMENT_PENDING', 'Payment Pending'), ('PAYMENT_SUCCESS', 'Payment Success'), ('PAYMENT_FAILED', 'Payment Failed'), ('REFUNDED', 'Refunded')], db_index=True, default='PAYMENT_SUCCESS', max_length=25)),
                ('payment_method', models.CharField(default='UPI', max_length=30)),
                ('pickup_start', models.CharField(blank=True, max_length=50)),
                ('pickup_end', models.CharField(blank=True, max_length=50)),
                ('pickup_code', models.CharField(blank=True, max_length=10)),
                ('notes', models.TextField(blank=True, default='')),
                ('cancellation_reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='marketplace.foodlisting')),
            ],
            options={
                'db_table': 'bookings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('type', models.CharField(choices=[('new_booking', 'New Booking Received'), ('status_update', 'Booking Status Updated'), ('cancellation', 'Booking Cancelled'), ('listing_update', 'Listing Update'), ('system', 'System Alert')], default='system', max_length=30)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('related_booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='marketplace.booking')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(db_index=True, max_length=150)),
                ('description', models.TextField(blank=True, default='')),
                ('category', models.CharField(default='Bakery & Cafe', help_text='e.g., Bakery, Cafe, Restaurant, Sweet Shop', max_length=60)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(default='Chandigarh', max_length=100)),
                ('phone', models.CharField(blank=True, default='', max_length=30)),
                ('banner_image', models.URLField(blank=True, default='', help_text='URL to restaurant header image or storefront photo')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('active', 'Active'), ('suspended', 'Suspended')], db_index=True, default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'restaurants',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='foodlisting',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='marketplace.restaurant'),
        ),
        migrations.AddField(
            model_name='booking',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='marketplace.restaurant'),
        ),
    ]
