# Generated by Django 6.1.1 on 2026-09-30 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodlisting',
            name='image',
            field=models.CharField(blank=True, default='assets/images/bakery_box.jpg', help_text='Food image URL or relative asset path', max_length=500),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='banner_image',
            field=models.CharField(blank=True, default='assets/images/hero_food.jpg', help_text='URL to restaurant header image or storefront photo', max_length=500),
        ),
    ]
