# Generated by Django 6.1.1 on 2026-09-30 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('customer', 'Customer'), ('restaurant', 'Restaurant'), ('business', 'Business'), ('admin', 'Admin')], default='customer', max_length=20),
        ),
    ]
