# Generated by Django 6.1.1 on 2026-10-02 17:12

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marketplace', '0003_booking_payment_timestamp_booking_razorpay_order_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('event_type', models.CharField(db_index=True, max_length=100)),
                ('payload', models.JSONField(default=dict)),
                ('processed', models.BooleanField(db_index=True, default=False)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'payment_webhook_events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razorpay_order_id', models.CharField(db_index=True, help_text='Razorpay order identifier returned by Orders API', max_length=100)),
                ('razorpay_payment_id', models.CharField(blank=True, db_index=True, help_text='Razorpay payment ID returned after successful authorization', max_length=100, null=True, unique=True)),
                ('razorpay_signature', models.CharField(blank=True, default='', help_text='HMAC SHA-256 signature returned by Razorpay Checkout', max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount in INR (Server-calculated)', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('status', models.CharField(choices=[('ORDER_CREATED', 'Order Created'), ('PAYMENT_PENDING', 'Payment Pending'), ('PAID', 'Paid'), ('PAYMENT_SUCCESS', 'Payment Success'), ('PAYMENT_FAILED', 'Payment Failed'), ('CANCELLED', 'Cancelled'), ('REFUND_PENDING', 'Refund Pending'), ('REFUNDED', 'Refunded')], db_index=True, default='ORDER_CREATED', max_length=30)),
                ('payment_method', models.CharField(blank=True, default='', max_length=50)),
                ('bank', models.CharField(blank=True, default='', max_length=50)),
                ('wallet', models.CharField(blank=True, default='', max_length=50)),
                ('vpa', models.CharField(blank=True, default='', max_length=100)),
                ('error_code', models.CharField(blank=True, default='', max_length=100)),
                ('error_description', models.TextField(blank=True, default='')),
                ('refund_status', models.CharField(blank=True, default='', max_length=30)),
                ('refund_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('refund_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='marketplace.booking')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payments',
                'ordering': ['-created_at'],
            },
        ),
    ]
